const BILDAZO_ARTICLE_PUBLISH_STATUSES = Object.freeze([
  "pending",
  "published",
  "already_imported",
  "needs_manual_review",
  "failed",
  "skipped",
]);

const BILDAZO_ARTICLE_PUBLISH_SUCCESS_STATUSES = Object.freeze([
  "published",
  "already_imported",
]);

const BILDAZO_ARTICLE_PUBLISH_RETRYABLE_STATUSES = Object.freeze([
  "pending",
  "failed",
  "needs_manual_review",
  "skipped",
]);

const BILDAZO_ARTICLE_PUBLISH_REMOTE_OK = Object.freeze([
  "approved",
  "already_imported",
]);

const BILDAZO_ARTICLE_PUBLISH_ERROR_CODES = Object.freeze({
  BILDAZO_ARTICLE_PUBLISH_DISABLED: "BILDAZO_ARTICLE_PUBLISH_DISABLED",
  BILDAZO_ARTICLE_PUBLISH_CONFIG_MISSING: "BILDAZO_ARTICLE_PUBLISH_CONFIG_MISSING",
  BILDAZO_ARTICLE_PUBLISH_TIMEOUT: "BILDAZO_ARTICLE_PUBLISH_TIMEOUT",
  BILDAZO_ARTICLE_PUBLISH_NETWORK: "BILDAZO_ARTICLE_PUBLISH_NETWORK",
  BILDAZO_ARTICLE_PUBLISH_HTTP_ERROR: "BILDAZO_ARTICLE_PUBLISH_HTTP_ERROR",
  BILDAZO_ARTICLE_PUBLISH_UNKNOWN_STATUS: "BILDAZO_ARTICLE_PUBLISH_UNKNOWN_STATUS",
  INVALID_BILDAZO_CATEGORY_MAPPING: "INVALID_BILDAZO_CATEGORY_MAPPING",
  BILDAZO_AUTHOR_NOT_LINKED: "BILDAZO_AUTHOR_NOT_LINKED",
  BILDAZO_AUTHOR_ID_INVALID: "BILDAZO_AUTHOR_ID_INVALID",
  MISSING_ARTICLE_CONTENT: "MISSING_ARTICLE_CONTENT",
  MISSING_FINAL_ARTICLE_CONTENT: "MISSING_FINAL_ARTICLE_CONTENT",
  SCHEMA_NOT_READY: "BILDAZO_ARTICLE_PUBLISH_SCHEMA_NOT_READY",
  APPLICATION_NOT_APPROVED: "APPLICATION_NOT_APPROVED",
});

module.exports = {
  BILDAZO_ARTICLE_PUBLISH_STATUSES,
  BILDAZO_ARTICLE_PUBLISH_SUCCESS_STATUSES,
  BILDAZO_ARTICLE_PUBLISH_RETRYABLE_STATUSES,
  BILDAZO_ARTICLE_PUBLISH_REMOTE_OK,
  BILDAZO_ARTICLE_PUBLISH_ERROR_CODES,
};
