/**
 * Phase A9.3 — Auto winner assignment constants (weighted fair lottery).
 */

const ACTIVATION_AUTO_ASSIGN_MODES = Object.freeze(["disabled", "weighted_fair"]);

const ACTIVATION_AUTO_ASSIGN_RUN_TYPES = Object.freeze([
  "auto_after_min_bidders",
  "manual_admin_run",
]);

const ACTIVATION_AUTO_ASSIGN_RUN_STATUSES = Object.freeze([
  "skipped",
  "completed",
  "failed",
]);

const ACTIVATION_WEIGHTED_FAIR_ALGORITHM_VERSION = "activation_weighted_fair_v1";

const ACTIVATION_AUTO_ASSIGN_OVERRIDE_REASON =
  "ACTIVATION_WEIGHTED_FAIR_AUTO_ASSIGN: system selected via seeded weighted lottery (A9.3).";

const ACTIVATION_AUTO_ASSIGN_ERROR_CODES = Object.freeze({
  SCHEMA_MISSING: "FREELANCER_ACTIVATION_AUTO_ASSIGN_SCHEMA_MISSING",
  DISABLED: "ACTIVATION_AUTO_ASSIGN_DISABLED",
  NOT_ACTIVATION_ARTICLE: "ACTIVATION_AUTO_ASSIGN_NOT_ACTIVATION_ARTICLE",
  ALREADY_ASSIGNED: "ACTIVATION_AUTO_ASSIGN_ALREADY_ASSIGNED",
  BELOW_MIN_BIDDERS: "ACTIVATION_AUTO_ASSIGN_BELOW_MIN_BIDDERS",
  NO_CANDIDATES: "ACTIVATION_AUTO_ASSIGN_NO_CANDIDATES",
  BLOCKED: "ACTIVATION_AUTO_ASSIGN_BLOCKED",
  BUDGET_INSUFFICIENT: "ACTIVATION_AUTO_ASSIGN_BUDGET_INSUFFICIENT",
  SELECTION_FAILED: "ACTIVATION_AUTO_ASSIGN_SELECTION_FAILED",
});

/** Integer milli-weights for deterministic lottery. */
const ACTIVATION_WEIGHTED_FAIR_WEIGHTS = Object.freeze({
  BASE: 1000,
  ZERO_WORK_BOOST: 5000,
  LOSS_PER: 800,
  EXTRA_LOSS_PER_AFTER_FIRST: 200,
  WAITING_DAY: 50,
  WAITING_DAY_CAP: 60,
  WIN_PENALTY: 3000,
  WORK_PENALTY: 1500,
  ACTIVE_ASSIGNED_PENALTY: 2000,
  MIN_WEIGHT: 1,
});

module.exports = {
  ACTIVATION_AUTO_ASSIGN_MODES,
  ACTIVATION_AUTO_ASSIGN_RUN_TYPES,
  ACTIVATION_AUTO_ASSIGN_RUN_STATUSES,
  ACTIVATION_WEIGHTED_FAIR_ALGORITHM_VERSION,
  ACTIVATION_AUTO_ASSIGN_OVERRIDE_REASON,
  ACTIVATION_AUTO_ASSIGN_ERROR_CODES,
  ACTIVATION_WEIGHTED_FAIR_WEIGHTS,
};
