/**
 * Phase A11 — Freelancer account activation KYC (company approval review).
 * Not marketplace article activation. Not Bid Credits. Not Bildazo.
 */

const ACCOUNT_ACTIVATION_KYC_TERMS_VERSION = "freelancer_account_activation_terms_2026-08-v1";

const ACCOUNT_ACTIVATION_KYC_TERMS_SNAPSHOT_AR = [
  "أوافق على شروط تفعيل حساب المستقل واستخدام منصة OrderzHouse.",
  "أتعهد بأن صور الهوية المرفقة صحيحة وتعود لي شخصيًا.",
  "أفهم أن إرسال الطلب لا يعني التفعيل الفوري، وأن الإدارة تراجع الطلب قبل الموافقة.",
].join("\n");

const ACCOUNT_ACTIVATION_REQUEST_STATUSES = Object.freeze([
  "draft",
  "pending_review",
  "approved",
  "rejected",
  "cancelled",
]);

const ACCOUNT_ACTIVATION_KYC_ALLOWED_MIME = Object.freeze([
  "image/jpeg",
  "image/png",
  "image/webp",
]);

const ACCOUNT_ACTIVATION_KYC_MAX_BYTES = 5 * 1024 * 1024;

const ACCOUNT_ACTIVATION_KYC_ERROR_CODES = Object.freeze({
  SCHEMA_NOT_READY: "ACCOUNT_ACTIVATION_KYC_SCHEMA_NOT_READY",
  FRONT_REQUIRED: "ACCOUNT_ACTIVATION_KYC_FRONT_REQUIRED",
  BACK_REQUIRED: "ACCOUNT_ACTIVATION_KYC_BACK_REQUIRED",
  TERMS_REQUIRED: "ACCOUNT_ACTIVATION_KYC_TERMS_REQUIRED",
  INVALID_FILE_TYPE: "ACCOUNT_ACTIVATION_KYC_INVALID_FILE_TYPE",
  FILE_TOO_LARGE: "ACCOUNT_ACTIVATION_KYC_FILE_TOO_LARGE",
  PENDING_EXISTS: "ACCOUNT_ACTIVATION_KYC_PENDING_EXISTS",
  ALREADY_APPROVED: "ACCOUNT_ACTIVATION_KYC_ALREADY_APPROVED",
  REQUEST_NOT_FOUND: "ACCOUNT_ACTIVATION_KYC_REQUEST_NOT_FOUND",
  NOT_PENDING: "ACCOUNT_ACTIVATION_KYC_NOT_PENDING",
  REJECTION_REASON_REQUIRED: "ACCOUNT_ACTIVATION_KYC_REJECTION_REASON_REQUIRED",
  SELF_ACTIVATE_DISABLED: "ACCOUNT_ACTIVATION_REQUIRES_KYC_REVIEW",
  /** A11.1 — staff/company-activate without KYC */
  FREELANCER_KYC_REQUIRED: "FREELANCER_KYC_REQUIRED",
  FREELANCER_KYC_PENDING_REVIEW: "FREELANCER_KYC_PENDING_REVIEW",
  FREELANCER_KYC_REJECTED: "FREELANCER_KYC_REJECTED",
  OVERRIDE_REASON_REQUIRED: "FREELANCER_KYC_OVERRIDE_REASON_REQUIRED",
  OVERRIDE_FORBIDDEN: "FREELANCER_KYC_OVERRIDE_FORBIDDEN",
});

module.exports = {
  ACCOUNT_ACTIVATION_KYC_TERMS_VERSION,
  ACCOUNT_ACTIVATION_KYC_TERMS_SNAPSHOT_AR,
  ACCOUNT_ACTIVATION_REQUEST_STATUSES,
  ACCOUNT_ACTIVATION_KYC_ALLOWED_MIME,
  ACCOUNT_ACTIVATION_KYC_MAX_BYTES,
  ACCOUNT_ACTIVATION_KYC_ERROR_CODES,
};
