/**
 * Legacy Freelancer contract field catalog (BATMAN TECHNOLOGY joining form).
 * Stable keys only. Super Admin configures per-campaign enable/required/label/order.
 */

const FIELD_TYPES = Object.freeze({
  TEXT: "text",
  TEXTAREA: "textarea",
  DATE: "date",
  NUMBER: "number",
  SELECT: "select",
  YES_NO: "yes_no",
  CHECKBOX: "checkbox",
  PHONE: "phone",
});

const SECTIONS = Object.freeze({
  PERSONAL: { key: "personal", labelAr: "البيانات الشخصية", sortOrder: 10 },
  ADDRESS: { key: "address", labelAr: "العنوان والتواصل", sortOrder: 20 },
  EDUCATION: { key: "education", labelAr: "المؤهلات العلمية", sortOrder: 30 },
  SKILLS: { key: "skills", labelAr: "المهارات", sortOrder: 40 },
  STUDY_WORK: { key: "study_work", labelAr: "الدراسة والعمل", sortOrder: 50 },
  EXTRA: { key: "extra", labelAr: "معلومات إضافية", sortOrder: 60 },
  DECLARATION: { key: "declaration", labelAr: "الإقرار وإنشاء الحساب", sortOrder: 70 },
});

/** System account fields — always required; Super Admin cannot disable. */
const SYSTEM_ACCOUNT_FIELDS = Object.freeze([
  { key: "email", labelAr: "البريد الإلكتروني", type: FIELD_TYPES.TEXT, system: true },
  { key: "phone", labelAr: "رقم الهاتف", type: FIELD_TYPES.PHONE, system: true },
  { key: "password", labelAr: "كلمة المرور", type: FIELD_TYPES.TEXT, system: true },
  { key: "password_confirm", labelAr: "تأكيد كلمة المرور", type: FIELD_TYPES.TEXT, system: true },
  { key: "terms_accepted", labelAr: "الموافقة على الشروط والأحكام", type: FIELD_TYPES.CHECKBOX, system: true },
  { key: "privacy_accepted", labelAr: "الموافقة على سياسة الخصوصية", type: FIELD_TYPES.CHECKBOX, system: true },
]);

const MARITAL_OPTIONS = Object.freeze([
  { value: "single", labelAr: "أعزب" },
  { value: "married", labelAr: "متزوج" },
  { value: "divorced", labelAr: "مطلق" },
  { value: "widowed", labelAr: "أرمل" },
  { value: "other", labelAr: "أخرى" },
]);

const HOW_HEARD_OPTIONS = Object.freeze([
  { value: "friend", labelAr: "صديق" },
  { value: "website", labelAr: "الموقع الإلكتروني" },
  { value: "recruitment_office", labelAr: "مكتب توظيف" },
  { value: "social_media", labelAr: "وسائل التواصل الاجتماعي" },
  { value: "other", labelAr: "أخرى" },
]);

/**
 * defaultEnabled / defaultRequired — applied when seeding a campaign.
 * conditional — { fieldKey, equals } — child visible/required only when parent matches.
 * sensitive — mask in lists; never put raw value in audit metadata.
 * canonicalUserColumn — optional users.* column to also update.
 */
const CONTRACT_FIELDS = Object.freeze([
  {
    key: "first_name",
    labelAr: "الاسم الأول",
    type: FIELD_TYPES.TEXT,
    section: SECTIONS.PERSONAL.key,
    sortOrder: 10,
    defaultEnabled: true,
    defaultRequired: true,
    canonicalUserColumn: "first_name",
  },
  {
    key: "father_name",
    labelAr: "اسم الأب",
    type: FIELD_TYPES.TEXT,
    section: SECTIONS.PERSONAL.key,
    sortOrder: 20,
    defaultEnabled: true,
    defaultRequired: true,
    canonicalUserColumn: "father_name",
  },
  {
    key: "family_name",
    labelAr: "اسم العائلة",
    type: FIELD_TYPES.TEXT,
    section: SECTIONS.PERSONAL.key,
    sortOrder: 30,
    defaultEnabled: true,
    defaultRequired: true,
    canonicalUserColumn: "family_name",
  },
  {
    key: "birth_date",
    labelAr: "تاريخ الميلاد",
    type: FIELD_TYPES.DATE,
    section: SECTIONS.PERSONAL.key,
    sortOrder: 40,
    defaultEnabled: true,
    defaultRequired: true,
  },
  {
    key: "birth_place",
    labelAr: "مكان الميلاد",
    type: FIELD_TYPES.TEXT,
    section: SECTIONS.PERSONAL.key,
    sortOrder: 50,
    defaultEnabled: false,
    defaultRequired: false,
  },
  {
    key: "nationality",
    labelAr: "الجنسية",
    type: FIELD_TYPES.TEXT,
    section: SECTIONS.PERSONAL.key,
    sortOrder: 60,
    defaultEnabled: true,
    defaultRequired: true,
  },
  {
    key: "marital_status",
    labelAr: "الحالة الاجتماعية",
    type: FIELD_TYPES.SELECT,
    section: SECTIONS.PERSONAL.key,
    sortOrder: 70,
    options: MARITAL_OPTIONS,
    defaultEnabled: false,
    defaultRequired: false,
  },
  {
    key: "national_id",
    labelAr: "الرقم الوطني",
    type: FIELD_TYPES.TEXT,
    section: SECTIONS.PERSONAL.key,
    sortOrder: 80,
    defaultEnabled: true,
    defaultRequired: true,
    sensitive: true,
  },
  {
    key: "children_count",
    labelAr: "عدد الأولاد",
    type: FIELD_TYPES.NUMBER,
    section: SECTIONS.PERSONAL.key,
    sortOrder: 90,
    defaultEnabled: false,
    defaultRequired: false,
  },
  {
    key: "social_security_number",
    labelAr: "رقم الضمان الاجتماعي",
    helperAr: "إن وجد",
    type: FIELD_TYPES.TEXT,
    section: SECTIONS.PERSONAL.key,
    sortOrder: 100,
    defaultEnabled: false,
    defaultRequired: false,
    sensitive: true,
  },
  {
    key: "city",
    labelAr: "المدينة",
    type: FIELD_TYPES.TEXT,
    section: SECTIONS.ADDRESS.key,
    sortOrder: 110,
    defaultEnabled: true,
    defaultRequired: true,
  },
  {
    key: "residence_area",
    labelAr: "منطقة السكن",
    type: FIELD_TYPES.TEXT,
    section: SECTIONS.ADDRESS.key,
    sortOrder: 120,
    defaultEnabled: true,
    defaultRequired: true,
  },
  {
    key: "education_level",
    labelAr: "المؤهل العلمي",
    type: FIELD_TYPES.TEXT,
    section: SECTIONS.EDUCATION.key,
    sortOrder: 130,
    defaultEnabled: true,
    defaultRequired: true,
  },
  {
    key: "specialization",
    labelAr: "التخصص",
    type: FIELD_TYPES.TEXT,
    section: SECTIONS.EDUCATION.key,
    sortOrder: 140,
    defaultEnabled: true,
    defaultRequired: true,
  },
  {
    key: "university_institute",
    labelAr: "المعهد / الجامعة",
    type: FIELD_TYPES.TEXT,
    section: SECTIONS.EDUCATION.key,
    sortOrder: 150,
    defaultEnabled: true,
    defaultRequired: false,
  },
  {
    key: "graduation_year",
    labelAr: "سنة التخرج",
    type: FIELD_TYPES.NUMBER,
    section: SECTIONS.EDUCATION.key,
    sortOrder: 160,
    defaultEnabled: true,
    defaultRequired: false,
  },
  {
    key: "academic_average",
    labelAr: "المعدل",
    type: FIELD_TYPES.TEXT,
    section: SECTIONS.EDUCATION.key,
    sortOrder: 170,
    defaultEnabled: false,
    defaultRequired: false,
  },
  {
    key: "skills_programs",
    labelAr: "المهارات والبرامج المتمكن منها",
    helperAr: "اكتب أسماء المهارات أو البرامج التي تتقنها بشكل واضح.",
    type: FIELD_TYPES.TEXTAREA,
    section: SECTIONS.SKILLS.key,
    sortOrder: 180,
    defaultEnabled: true,
    defaultRequired: true,
    canonicalUserColumn: "skills",
  },
  {
    key: "freelance_joining_skills",
    labelAr: "ما هي المهارات التي تريد الانضمام بها كفريلانسر؟",
    type: FIELD_TYPES.TEXTAREA,
    section: SECTIONS.SKILLS.key,
    sortOrder: 190,
    defaultEnabled: true,
    defaultRequired: true,
  },
  {
    key: "is_university_student",
    labelAr: "هل أنت طالب جامعي؟",
    type: FIELD_TYPES.YES_NO,
    section: SECTIONS.STUDY_WORK.key,
    sortOrder: 200,
    defaultEnabled: true,
    defaultRequired: true,
  },
  {
    key: "current_university",
    labelAr: "أين تدرس؟",
    type: FIELD_TYPES.TEXT,
    section: SECTIONS.STUDY_WORK.key,
    sortOrder: 210,
    defaultEnabled: true,
    defaultRequired: true,
    conditional: { fieldKey: "is_university_student", equals: true },
  },
  {
    key: "has_university_commitments",
    labelAr: "هل يوجد عليك التزامات أو أقساط جامعية؟",
    type: FIELD_TYPES.YES_NO,
    section: SECTIONS.STUDY_WORK.key,
    sortOrder: 220,
    defaultEnabled: false,
    defaultRequired: false,
    conditional: { fieldKey: "is_university_student", equals: true },
  },
  {
    key: "university_commitment_value",
    labelAr: "قيمة الالتزامات الجامعية",
    type: FIELD_TYPES.NUMBER,
    section: SECTIONS.STUDY_WORK.key,
    sortOrder: 230,
    defaultEnabled: false,
    defaultRequired: false,
    conditional: { fieldKey: "has_university_commitments", equals: true },
    informationalOnly: true,
  },
  {
    key: "is_currently_employed",
    labelAr: "هل أنت على رأس عملك؟",
    type: FIELD_TYPES.YES_NO,
    section: SECTIONS.STUDY_WORK.key,
    sortOrder: 240,
    defaultEnabled: true,
    defaultRequired: true,
  },
  {
    key: "current_employer",
    labelAr: "أين تعمل؟",
    type: FIELD_TYPES.TEXT,
    section: SECTIONS.STUDY_WORK.key,
    sortOrder: 250,
    defaultEnabled: true,
    defaultRequired: true,
    conditional: { fieldKey: "is_currently_employed", equals: true },
  },
  {
    key: "how_heard_about_freelance",
    labelAr: "كيف سمعت عن العمل الحر؟",
    type: FIELD_TYPES.SELECT,
    section: SECTIONS.EXTRA.key,
    sortOrder: 260,
    options: HOW_HEARD_OPTIONS,
    defaultEnabled: false,
    defaultRequired: false,
  },
  {
    key: "referral_friend_name",
    labelAr: "اسم الصديق",
    type: FIELD_TYPES.TEXT,
    section: SECTIONS.EXTRA.key,
    sortOrder: 270,
    defaultEnabled: false,
    defaultRequired: false,
    conditional: { fieldKey: "how_heard_about_freelance", equals: "friend" },
  },
  {
    key: "reference_1_name",
    labelAr: "اسم المعرّف الأول",
    type: FIELD_TYPES.TEXT,
    section: SECTIONS.EXTRA.key,
    sortOrder: 280,
    defaultEnabled: false,
    defaultRequired: false,
  },
  {
    key: "reference_1_phone",
    labelAr: "هاتف المعرّف الأول",
    type: FIELD_TYPES.PHONE,
    section: SECTIONS.EXTRA.key,
    sortOrder: 290,
    defaultEnabled: false,
    defaultRequired: false,
    sensitive: true,
  },
  {
    key: "reference_1_job",
    labelAr: "وظيفة المعرّف الأول",
    type: FIELD_TYPES.TEXT,
    section: SECTIONS.EXTRA.key,
    sortOrder: 300,
    defaultEnabled: false,
    defaultRequired: false,
  },
  {
    key: "reference_2_name",
    labelAr: "اسم المعرّف الثاني",
    type: FIELD_TYPES.TEXT,
    section: SECTIONS.EXTRA.key,
    sortOrder: 310,
    defaultEnabled: false,
    defaultRequired: false,
  },
  {
    key: "reference_2_phone",
    labelAr: "هاتف المعرّف الثاني",
    type: FIELD_TYPES.PHONE,
    section: SECTIONS.EXTRA.key,
    sortOrder: 320,
    defaultEnabled: false,
    defaultRequired: false,
    sensitive: true,
  },
  {
    key: "reference_2_job",
    labelAr: "وظيفة المعرّف الثاني",
    type: FIELD_TYPES.TEXT,
    section: SECTIONS.EXTRA.key,
    sortOrder: 330,
    defaultEnabled: false,
    defaultRequired: false,
  },
  {
    key: "information_declaration",
    labelAr: "إقرار بصحة المعلومات",
    helperAr: "أقر بأن المعلومات التي قدمتها صحيحة وكاملة.",
    type: FIELD_TYPES.CHECKBOX,
    section: SECTIONS.DECLARATION.key,
    sortOrder: 340,
    defaultEnabled: true,
    defaultRequired: true,
  },
]);

const CONTRACT_FIELD_BY_KEY = Object.freeze(
  Object.fromEntries(CONTRACT_FIELDS.map((f) => [f.key, f])),
);

const SENSITIVE_FIELD_KEYS = Object.freeze(
  CONTRACT_FIELDS.filter((f) => f.sensitive).map((f) => f.key),
);

function getContractCatalog() {
  return {
    systemAccountFields: SYSTEM_ACCOUNT_FIELDS.map((f) => ({ ...f })),
    sections: Object.values(SECTIONS).map((s) => ({ ...s })),
    fields: CONTRACT_FIELDS.map((f) => ({
      key: f.key,
      labelAr: f.labelAr,
      helperAr: f.helperAr || null,
      type: f.type,
      section: f.section,
      sortOrder: f.sortOrder,
      options: f.options ? f.options.map((o) => ({ ...o })) : null,
      conditional: f.conditional ? { ...f.conditional } : null,
      defaultEnabled: Boolean(f.defaultEnabled),
      defaultRequired: Boolean(f.defaultRequired),
      sensitive: Boolean(f.sensitive),
      informationalOnly: Boolean(f.informationalOnly),
      canonicalUserColumn: f.canonicalUserColumn || null,
    })),
  };
}

function getDefaultFieldSeedRows() {
  return CONTRACT_FIELDS.map((f) => ({
    fieldKey: f.key,
    labelAr: f.labelAr,
    isEnabled: Boolean(f.defaultEnabled),
    isRequired: Boolean(f.defaultRequired),
    sortOrder: f.sortOrder,
    configJson: {
      helperAr: f.helperAr || null,
      type: f.type,
      section: f.section,
      options: f.options || null,
      conditional: f.conditional || null,
      sensitive: Boolean(f.sensitive),
    },
  }));
}

module.exports = {
  FIELD_TYPES,
  SECTIONS,
  SYSTEM_ACCOUNT_FIELDS,
  CONTRACT_FIELDS,
  CONTRACT_FIELD_BY_KEY,
  SENSITIVE_FIELD_KEYS,
  MARITAL_OPTIONS,
  HOW_HEARD_OPTIONS,
  getContractCatalog,
  getDefaultFieldSeedRows,
};
