/**
 * Phase D1 — Super Admin Bid Distribution Pool constants.
 * Independent Bid source: admin_distribution_pool.
 */

const ADMIN_BID_POOL_GRANT_SOURCE = "admin_distribution_pool";
const ADMIN_DISTRIBUTION_POOL_GRANT_EVENT = "ADMIN_DISTRIBUTION_POOL_GRANT";

const BID_POOL_TOTAL_SOURCE = "SERVER_CALCULATION";
const POOL_EXPIRED_UNUSED_BIDS_RETURN = "100_PERCENT";
const POOL_CONSUMED_BIDS_RETURN = "NONE";
const BID_POOL_WORK_TOKEN_RUNTIME = "NONE";

const BID_POOL_STATUSES = Object.freeze(["active", "closed"]);
const BID_POOL_DISTRIBUTION_MODES = Object.freeze(["manual", "random"]);
const BID_POOL_EXPIRATION_MODES = Object.freeze(["days", "weeks", "exact_datetime"]);
const BID_POOL_EVENT_TYPES = Object.freeze(["POOL_CREATED", "ALLOCATED", "RETURNED_UNUSED"]);
const BID_POOL_ALLOCATION_STATUSES = Object.freeze(["active", "returned"]);

const BID_POOL_ERROR_CODES = Object.freeze({
  BID_POOL_SCHEMA_NOT_READY: "BID_POOL_SCHEMA_NOT_READY",
  INVALID_POOL_BUDGET: "INVALID_POOL_BUDGET",
  INVALID_BID_UNIT_PRICE: "INVALID_BID_UNIT_PRICE",
  POOL_TOTAL_BIDS_ZERO: "POOL_TOTAL_BIDS_ZERO",
  POOL_NOT_FOUND: "POOL_NOT_FOUND",
  POOL_NOT_ACTIVE: "POOL_NOT_ACTIVE",
  POOL_INSUFFICIENT_BIDS: "POOL_INSUFFICIENT_BIDS",
  INVALID_DISTRIBUTION_MODE: "INVALID_DISTRIBUTION_MODE",
  INVALID_RECIPIENTS: "INVALID_RECIPIENTS",
  DUPLICATE_RECIPIENT: "DUPLICATE_RECIPIENT",
  INVALID_FREELANCER: "INVALID_FREELANCER",
  INVALID_EXPIRATION: "INVALID_EXPIRATION",
  BATCH_IDEMPOTENT: "BATCH_IDEMPOTENT",
});

module.exports = {
  ADMIN_BID_POOL_GRANT_SOURCE,
  ADMIN_DISTRIBUTION_POOL_GRANT_EVENT,
  BID_POOL_TOTAL_SOURCE,
  POOL_EXPIRED_UNUSED_BIDS_RETURN,
  POOL_CONSUMED_BIDS_RETURN,
  BID_POOL_WORK_TOKEN_RUNTIME,
  BID_POOL_STATUSES,
  BID_POOL_DISTRIBUTION_MODES,
  BID_POOL_EXPIRATION_MODES,
  BID_POOL_EVENT_TYPES,
  BID_POOL_ALLOCATION_STATUSES,
  BID_POOL_ERROR_CODES,
};
