/**
 * Phase E2 — Article Economy product constants.
 * Monetary defaults are seeded in Migration 154; runtime reads DB config.
 */

const ARTICLE_VALUE_STARTER_JOD = "1.000";
const ARTICLE_VALUE_SILVER_JOD = "2.000";
const ARTICLE_VALUE_PRO_JOD = "3.000";
const ARTICLE_VALUE_ELITE_JOD = "4.000";

const ARTICLE_COMPANY_SHARE_PERCENT = 30;
const ARTICLE_REVIEWER_FEE_JOD = "0.200";
const ARTICLE_DEFAULT_BID_COST = 1;

const ARTICLE_APPLICATION_BID_BEHAVIOR =
  "RESERVE_ON_APPLICATION_CONSUME_ON_FINAL_APPROVAL";
const ARTICLE_APPLICATION_FINAL_BID_CONSUME_TIME = "FINAL_ARTICLE_APPROVAL";
const OLD_ARTICLE_APPLICATION_IMMEDIATE_BID_CHARGE = "DEPRECATED_INACTIVE";

const STARTER_ARTICLE_WRITER_EARNINGS = "PENDING_UNTIL_ELIGIBLE_UPGRADE";
const STARTER_PENDING_EARNINGS_RELEASE_TRIGGER = "PAID_MEMBERSHIP_ACTIVATION";

const ARTICLE_CAMPAIGN_AUTO_STOP = "ENABLED";
const ARTICLE_APPROVAL_CAPACITY_CONCURRENCY = "SAFE";
const BILDAZO_PUBLISH_FAILURE_REPEATS_FINANCIAL_SETTLEMENT = "NO";

const ARTICLE_ECONOMIC_SNAPSHOT_POINT = "ASSIGNMENT_SELECTION";

const ARTICLE_DESTINATION_BILDAZO = "bildazo";

const ARTICLE_APPLICATION_WORKFLOW_STATUSES = Object.freeze([
  "pending",
  "selected",
  "assigned",
  "writing",
  "submitted",
  "under_review",
  "revision_requested",
  "approved",
  "rejected",
  "withdrawn",
  "cancelled",
]);

const ARTICLE_TERMINAL_RELEASE_STATUSES = Object.freeze([
  "rejected",
  "withdrawn",
  "cancelled",
]);

const ARTICLE_E2_ERROR_CODES = Object.freeze({
  ARTICLE_ECONOMY_INVALID_SPLIT: "ARTICLE_ECONOMY_INVALID_SPLIT",
  ARTICLE_CAMPAIGN_TARGET_EXHAUSTED: "ARTICLE_CAMPAIGN_TARGET_EXHAUSTED",
  ARTICLE_CAMPAIGN_BUDGET_EXHAUSTED: "ARTICLE_CAMPAIGN_BUDGET_EXHAUSTED",
  ARTICLE_CAMPAIGN_DEADLINE_PASSED: "ARTICLE_CAMPAIGN_DEADLINE_PASSED",
  ARTICLE_CAMPAIGN_NOT_ELIGIBLE_TIER: "ARTICLE_CAMPAIGN_NOT_ELIGIBLE_TIER",
  ARTICLE_BID_RESERVATION_REQUIRED: "ARTICLE_BID_RESERVATION_REQUIRED",
  ARTICLE_SETTLEMENT_ALREADY_EXISTS: "ARTICLE_SETTLEMENT_ALREADY_EXISTS",
  ARTICLE_SNAPSHOT_REQUIRED: "ARTICLE_SNAPSHOT_REQUIRED",
  ARTICLE_RESERVATION_NOT_ACTIVE: "ARTICLE_RESERVATION_NOT_ACTIVE",
  BILDAZO_OUTBOX_ENQUEUE_FAILED: "BILDAZO_OUTBOX_ENQUEUE_FAILED",
});

module.exports = {
  ARTICLE_VALUE_STARTER_JOD,
  ARTICLE_VALUE_SILVER_JOD,
  ARTICLE_VALUE_PRO_JOD,
  ARTICLE_VALUE_ELITE_JOD,
  ARTICLE_COMPANY_SHARE_PERCENT,
  ARTICLE_REVIEWER_FEE_JOD,
  ARTICLE_DEFAULT_BID_COST,
  ARTICLE_APPLICATION_BID_BEHAVIOR,
  ARTICLE_APPLICATION_FINAL_BID_CONSUME_TIME,
  OLD_ARTICLE_APPLICATION_IMMEDIATE_BID_CHARGE,
  STARTER_ARTICLE_WRITER_EARNINGS,
  STARTER_PENDING_EARNINGS_RELEASE_TRIGGER,
  ARTICLE_CAMPAIGN_AUTO_STOP,
  ARTICLE_APPROVAL_CAPACITY_CONCURRENCY,
  BILDAZO_PUBLISH_FAILURE_REPEATS_FINANCIAL_SETTLEMENT,
  ARTICLE_ECONOMIC_SNAPSHOT_POINT,
  ARTICLE_DESTINATION_BILDAZO,
  ARTICLE_APPLICATION_WORKFLOW_STATUSES,
  ARTICLE_TERMINAL_RELEASE_STATUSES,
  ARTICLE_E2_ERROR_CODES,
};
