/**
 * Phase B6 — Bid Credit package commercial purchase + payment reversal constants.
 */

const BID_PACKAGE_PURCHASE_PURPOSE = "bid_credit_package_purchase";
const BID_PACKAGE_PURCHASE_PROVIDER = "stripe";
const BID_PACKAGE_PURCHASE_CURRENCY = "JOD";

const BID_PACKAGE_PURCHASE_STATUSES = Object.freeze([
  "pending",
  "checkout_created",
  "paid",
  "fulfilled",
  "cancelled",
  "failed",
]);

const BID_PACKAGE_PAYMENT_REVERSAL_STATUSES = Object.freeze([
  "none",
  "dispute_open",
  "dispute_won",
  "dispute_lost",
  "refunded_full",
  "refunded_partial_manual_review",
  "manual_resolved_released",
  "manual_resolved_revoked",
  "manual_resolved_kept_frozen",
]);

const BID_PACKAGE_MANUAL_REVIEW_RESOLUTIONS = Object.freeze([
  "keep_frozen",
  "release_remaining",
  "revoke_remaining",
]);

const BID_PACKAGE_PURCHASE_GRANT_SOURCE = "package_purchase";
const BID_PACKAGE_PURCHASE_LEDGER_EVENT = "BID_PACKAGE_PURCHASE_GRANT";
const BID_PACKAGE_PURCHASE_REVOKE_LEDGER_EVENT = "BID_PACKAGE_PURCHASE_REVOKE";

const BID_PACKAGE_PAYMENT_AMOUNT_SOURCE = "SERVER_PACKAGE_SNAPSHOT";
const CLIENT_CONTROLLED_BID_PURCHASE_ECONOMICS = "NONE";
const PURCHASED_BIDS_MEMBERSHIP_INDEPENDENT = "YES";
const PURCHASED_BIDS_FEFO = "EXISTING_ENGINE";
const PURCHASE_REVERSAL_FEFO_ENGINE = "EXISTING_BID_FEFO";
const BID_PACKAGE_WORK_TOKEN_RUNTIME = "NONE";
const BID_PACKAGE_PURCHASE_HISTORICAL_BACKFILL = "NONE";
const BID_PACKAGE_PURCHASE_REVERSAL_HISTORICAL_BACKFILL = "NONE";
const BID_CREDIT_PURCHASES_ENGINE = "DORMANT";
const STRIPE_SUCCESS_PAGE_CAN_GRANT_BIDS = "NO";

/** Owner-approved commercial reversal policy (B6 finalize). */
const BID_PACKAGE_PAYMENT_REFUND_POLICY = "OWNER_APPROVED_B6";
const BID_PACKAGE_FULL_REFUND = "REVOKE_UNUSED_PURCHASE_BIDS_ONLY";
const BID_PACKAGE_ALREADY_CONSUMED_REFUND = "NO_CLAWBACK_NO_NEGATIVE_BALANCE";
const BID_PACKAGE_CROSS_SOURCE_CLAWBACK = "NONE";
const BID_PACKAGE_ACTIVE_DISPUTE = "FREEZE_PURCHASE_REMAINDER_ONLY";
const BID_PACKAGE_DISPUTE_WON = "UNFREEZE_IF_STILL_VALID";
const BID_PACKAGE_DISPUTE_LOST = "REVOKE_UNUSED_PURCHASE_REMAINDER";
const PARTIAL_BID_PACKAGE_REFUND_POLICY = "MANUAL_REVIEW";
const ACTIVE_DISPUTE_ACCOUNT_SUSPENSION = "NONE";
const DISPUTE_FREEZE_EXTENDS_BID_EXPIRY = "NO";
const BID_PURCHASE_REFUND_NEGATIVE_BALANCE = "NONE";
const BID_PURCHASE_REFUND_CROSS_SOURCE_CLAWBACK = "NONE";
const BID_PURCHASE_REFUND_ALREADY_CONSUMED_BIDS = "AUDIT_ONLY_NO_CLAWBACK";
const ACTIVE_DISPUTE_PURCHASE_BIDS = "FROZEN_PENDING_RESOLUTION";
const DISPUTE_WON_PURCHASE_BIDS = "UNFREEZE_EXISTING_REMAINDER";
const DISPUTE_LOST_PURCHASE_BIDS = "REVOKE_UNUSED_REMAINDER";

const BID_PACKAGE_PURCHASE_ERROR_CODES = Object.freeze({
  BID_CREDIT_PURCHASES_ENGINE_OFF: "BID_CREDIT_PURCHASES_ENGINE_OFF",
  BID_CREDITS_ENGINE_OFF: "BID_CREDITS_ENGINE_OFF",
  BID_PURCHASES_SCHEMA_NOT_READY: "BID_PURCHASES_SCHEMA_NOT_READY",
  BID_PACKAGE_NOT_FOUND: "BID_PACKAGE_NOT_FOUND",
  BID_PACKAGE_INACTIVE: "BID_PACKAGE_INACTIVE",
  BID_PACKAGE_NOT_PURCHASABLE: "BID_PACKAGE_NOT_PURCHASABLE",
  BID_PURCHASE_NOT_FOUND: "BID_PURCHASE_NOT_FOUND",
  BID_PURCHASE_PAYMENT_MISMATCH: "BID_PURCHASE_PAYMENT_MISMATCH",
  BID_PURCHASE_NOT_PAID: "BID_PURCHASE_NOT_PAID",
  BID_PURCHASE_FORBIDDEN: "BID_PURCHASE_FORBIDDEN",
  BID_PURCHASE_REVERSAL_NOT_ALLOWED: "BID_PURCHASE_REVERSAL_NOT_ALLOWED",
  BID_PURCHASE_MANUAL_REVIEW_REQUIRED: "BID_PURCHASE_MANUAL_REVIEW_REQUIRED",
  INVALID_FREELANCER: "INVALID_FREELANCER",
});

const TERMINAL_REVERSAL_STATUSES = new Set([
  "refunded_full",
  "dispute_lost",
  "manual_resolved_revoked",
]);

function buildBidPackagePurchaseCheckoutIdempotencyKey(freelancerUserId, packageId, nonce) {
  return `bid_pkg_checkout:freelancer:${Number(freelancerUserId)}:package:${Number(packageId)}:${String(nonce)}`;
}

function buildBidPackagePurchaseGrantIdempotencyKey(purchaseId) {
  return `bid_pkg_purchase_grant:purchase:${Number(purchaseId)}`;
}

function buildBidPackagePurchaseRevokeIdempotencyKey(purchaseId, reason) {
  return `bid_pkg_purchase_revoke:purchase:${Number(purchaseId)}:${String(reason || "revoke")}`;
}

function unusedRemainderFromGrant(grantRow) {
  if (!grantRow) return 0;
  const granted = Number(grantRow.amount_granted) || 0;
  const consumed = Number(grantRow.amount_consumed) || 0;
  const expired = Number(grantRow.amount_expired) || 0;
  const revoked = Number(grantRow.amount_revoked) || 0;
  return Math.max(0, granted - consumed - expired - revoked);
}

module.exports = {
  BID_PACKAGE_PURCHASE_PURPOSE,
  BID_PACKAGE_PURCHASE_PROVIDER,
  BID_PACKAGE_PURCHASE_CURRENCY,
  BID_PACKAGE_PURCHASE_STATUSES,
  BID_PACKAGE_PAYMENT_REVERSAL_STATUSES,
  BID_PACKAGE_MANUAL_REVIEW_RESOLUTIONS,
  BID_PACKAGE_PURCHASE_GRANT_SOURCE,
  BID_PACKAGE_PURCHASE_LEDGER_EVENT,
  BID_PACKAGE_PURCHASE_REVOKE_LEDGER_EVENT,
  BID_PACKAGE_PAYMENT_AMOUNT_SOURCE,
  CLIENT_CONTROLLED_BID_PURCHASE_ECONOMICS,
  PURCHASED_BIDS_MEMBERSHIP_INDEPENDENT,
  PURCHASED_BIDS_FEFO,
  PURCHASE_REVERSAL_FEFO_ENGINE,
  BID_PACKAGE_WORK_TOKEN_RUNTIME,
  BID_PACKAGE_PURCHASE_HISTORICAL_BACKFILL,
  BID_PACKAGE_PURCHASE_REVERSAL_HISTORICAL_BACKFILL,
  BID_CREDIT_PURCHASES_ENGINE,
  STRIPE_SUCCESS_PAGE_CAN_GRANT_BIDS,
  BID_PACKAGE_PAYMENT_REFUND_POLICY,
  BID_PACKAGE_FULL_REFUND,
  BID_PACKAGE_ALREADY_CONSUMED_REFUND,
  BID_PACKAGE_CROSS_SOURCE_CLAWBACK,
  BID_PACKAGE_ACTIVE_DISPUTE,
  BID_PACKAGE_DISPUTE_WON,
  BID_PACKAGE_DISPUTE_LOST,
  PARTIAL_BID_PACKAGE_REFUND_POLICY,
  ACTIVE_DISPUTE_ACCOUNT_SUSPENSION,
  DISPUTE_FREEZE_EXTENDS_BID_EXPIRY,
  BID_PURCHASE_REFUND_NEGATIVE_BALANCE,
  BID_PURCHASE_REFUND_CROSS_SOURCE_CLAWBACK,
  BID_PURCHASE_REFUND_ALREADY_CONSUMED_BIDS,
  ACTIVE_DISPUTE_PURCHASE_BIDS,
  DISPUTE_WON_PURCHASE_BIDS,
  DISPUTE_LOST_PURCHASE_BIDS,
  BID_PACKAGE_PURCHASE_ERROR_CODES,
  TERMINAL_REVERSAL_STATUSES,
  buildBidPackagePurchaseCheckoutIdempotencyKey,
  buildBidPackagePurchaseGrantIdempotencyKey,
  buildBidPackagePurchaseRevokeIdempotencyKey,
  unusedRemainderFromGrant,
};
