/**
 * Phase 6 — Priority Bid Auction constants / error codes.
 * Separate from Phase 5 NORMAL_APPLICATION_* economics.
 */

const PRIORITY_AUCTION_STATUSES = Object.freeze([
  "scheduled",
  "active",
  "resolving",
  "resolved",
  "cancelled",
]);

const PRIORITY_AUCTION_BID_STATUSES = Object.freeze([
  "active",
  "won",
  "lost",
  "cancelled",
  "skipped_ineligible",
  "released",
]);

const PRIORITY_AUCTION_RESOLUTION_REASONS = Object.freeze({
  HIGHEST_TOKEN_WON: "HIGHEST_TOKEN_WON",
  NO_ELIGIBLE_WINNER: "NO_ELIGIBLE_WINNER",
  ORDER_CANCELLED_BEFORE_RESOLUTION: "ORDER_CANCELLED_BEFORE_RESOLUTION",
  CANCELLED_BEFORE_RESOLUTION: "CANCELLED_BEFORE_RESOLUTION",
  ALREADY_RESOLVED: "ALREADY_RESOLVED",
});

const PRIORITY_AUCTION_REFERENCE_TYPES = Object.freeze({
  BID: "priority_auction_bid",
  AUCTION: "priority_auction",
});

const PRIORITY_BID_RESERVE_EVENT = "PRIORITY_BID_RESERVE";
const PRIORITY_BID_INCREASE_RESERVE_EVENT = "PRIORITY_BID_INCREASE_RESERVE";
const PRIORITY_BID_RELEASE_EVENT = "PRIORITY_BID_RELEASE";
const PRIORITY_BID_CONSUME_EVENT = "PRIORITY_BID_CONSUME";

const PRIORITY_AUCTION_ERROR_CODES = Object.freeze({
  PRIORITY_AUCTION_ENGINE_OFF: "PRIORITY_AUCTION_ENGINE_OFF",
  PRIORITY_AUCTION_DEPRECATED: "PRIORITY_AUCTION_DEPRECATED",
  PRIORITY_AUCTION_NOT_FOUND: "PRIORITY_AUCTION_NOT_FOUND",
  PRIORITY_AUCTION_NOT_ACTIVE: "PRIORITY_AUCTION_NOT_ACTIVE",
  PRIORITY_AUCTION_ALREADY_EXISTS: "PRIORITY_AUCTION_ALREADY_EXISTS",
  PRIORITY_AUCTION_CLOSED: "PRIORITY_AUCTION_CLOSED",
  PRIORITY_AUCTION_ORDER_INELIGIBLE: "PRIORITY_AUCTION_ORDER_INELIGIBLE",
  PRIORITY_BID_DECREASE_NOT_ALLOWED: "PRIORITY_BID_DECREASE_NOT_ALLOWED",
  PRIORITY_BID_WITHDRAWAL_NOT_ALLOWED: "PRIORITY_BID_WITHDRAWAL_NOT_ALLOWED",
  PRIORITY_BID_BELOW_MINIMUM: "PRIORITY_BID_BELOW_MINIMUM",
  PRIORITY_BID_ABOVE_MAXIMUM: "PRIORITY_BID_ABOVE_MAXIMUM",
  PRIORITY_BID_ALREADY_EXISTS: "PRIORITY_BID_ALREADY_EXISTS",
  PRIORITY_BID_NOT_FOUND: "PRIORITY_BID_NOT_FOUND",
  PRIORITY_BID_INCREASE_REQUIRED: "PRIORITY_BID_INCREASE_REQUIRED",
  PRIORITY_BID_INSUFFICIENT_USES: "PRIORITY_BID_INSUFFICIENT_USES",
  PRIORITY_AUCTION_FAKE_TRAINING_FORBIDDEN: "PRIORITY_AUCTION_FAKE_TRAINING_FORBIDDEN",
  PRIORITY_BID_AUCTION_ACTIVE: "PRIORITY_BID_AUCTION_ACTIVE",
  PRIORITY_AUCTION_NOT_PRICED_BIDDING: "PRIORITY_AUCTION_NOT_PRICED_BIDDING",
  /** @deprecated Resolved — automatic creation on priced-bidding open is approved. */
  PRIORITY_AUCTION_CREATION_TRIGGER_DECISION_REQUIRED:
    "PRIORITY_AUCTION_CREATION_TRIGGER_DECISION_REQUIRED",
});

const PRIORITY_AUCTION_CREATION_SOURCES = Object.freeze({
  AUTOMATIC_PRICED_BIDDING_OPEN: "automatic_priced_bidding_open",
  SUPER_ADMIN_MANUAL: "super_admin_manual",
  SYSTEM: "system",
});

module.exports = {
  PRIORITY_AUCTION_STATUSES,
  PRIORITY_AUCTION_BID_STATUSES,
  PRIORITY_AUCTION_RESOLUTION_REASONS,
  PRIORITY_AUCTION_REFERENCE_TYPES,
  PRIORITY_AUCTION_CREATION_SOURCES,
  PRIORITY_BID_RESERVE_EVENT,
  PRIORITY_BID_INCREASE_RESERVE_EVENT,
  PRIORITY_BID_RELEASE_EVENT,
  PRIORITY_BID_CONSUME_EVENT,
  PRIORITY_AUCTION_ERROR_CODES,
};
