/**
 * Phase 7 Fair Distribution — lexicographic COUNT-ONLY queue (no numeric fairness_score).
 */

const FAIR_DISTRIBUTION_ERROR_CODES = Object.freeze({
  FAIR_DISTRIBUTION_ENGINE_OFF: "FAIR_DISTRIBUTION_ENGINE_OFF",
  FAIR_DISTRIBUTION_HYBRID_WEIGHT_POLICY_REQUIRED: "FAIR_DISTRIBUTION_HYBRID_WEIGHT_POLICY_REQUIRED",
  FAIR_DISTRIBUTION_NO_ELIGIBLE_CANDIDATES: "FAIR_DISTRIBUTION_NO_ELIGIBLE_CANDIDATES",
  FAIR_DISTRIBUTION_ORDER_INELIGIBLE: "FAIR_DISTRIBUTION_ORDER_INELIGIBLE",
  FAIR_DISTRIBUTION_SCHEMA_MISSING: "FAIR_DISTRIBUTION_SCHEMA_MISSING",
});

const FAIR_DISTRIBUTION_REASON_CODES = Object.freeze({
  FEWER_RECENT_ASSIGNMENTS: "FEWER_RECENT_ASSIGNMENTS",
  MORE_WAITING_LOSSES: "MORE_WAITING_LOSSES",
  LOWER_ACTIVE_WORKLOAD: "LOWER_ACTIVE_WORKLOAD",
  LONGER_SINCE_PREVIOUS_ASSIGNMENT: "LONGER_SINCE_PREVIOUS_ASSIGNMENT",
  NO_PREVIOUS_ASSIGNMENT_IN_SCOPE: "NO_PREVIOUS_ASSIGNMENT_IN_SCOPE",
  PRIORITY_TOKEN_TIE_BREAK: "PRIORITY_TOKEN_TIE_BREAK",
  EARLIER_SUBMITTED_AT: "EARLIER_SUBMITTED_AT",
  STABLE_ID_TIE_BREAK: "STABLE_ID_TIE_BREAK",
  SELECTED_BY_HIGHEST_TOKEN_ONLY: "SELECTED_BY_HIGHEST_TOKEN_ONLY",
  CANDIDATE_NOT_ELIGIBLE: "CANDIDATE_NOT_ELIGIBLE",
  FAIR_DISTRIBUTION_FIRST_SELECTED: "FAIR_DISTRIBUTION_FIRST_SELECTED",
});

/** Active real work statuses that count toward current workload. */
const FAIR_ACTIVE_WORKLOAD_STATUSES = Object.freeze([
  "assigned",
  "in_progress",
  "ready_for_work",
  "pending_client_review",
  "pending_freelancer_acceptance",
]);

/**
 * Effective assignment: Freelancer genuinely received work (received_at set).
 * selected_pending_payment alone does NOT count.
 */
const FAIR_EFFECTIVE_ASSIGNMENT_REQUIRES_RECEIVED_AT = true;

module.exports = {
  FAIR_DISTRIBUTION_ERROR_CODES,
  FAIR_DISTRIBUTION_REASON_CODES,
  FAIR_ACTIVE_WORKLOAD_STATUSES,
  FAIR_EFFECTIVE_ASSIGNMENT_REQUIRES_RECEIVED_AT,
};
