/**
 * Marketplace Work Token Wallet / Ledger / Reservation constants — Phase 4.
 * Accounting vocabulary only. Engines remain OFF until later phases.
 */

const WORK_TOKEN_RESERVATION_STATUSES = Object.freeze([
  "active",
  "released",
  "consumed",
  "cancelled",
]);

const WORK_TOKEN_BALANCE_EFFECTS = Object.freeze([
  "credit_available",
  "reserve",
  "release",
  "consume_reserved",
  "consume_available",
]);

/**
 * Ledger event types. Priority Bid events are reserved for Phase 6 callers.
 * Phase 4 provides primitives; does not run auctions.
 */
const WORK_TOKEN_LEDGER_EVENT_TYPES = Object.freeze([
  "TOKEN_CREDIT",
  "TOKEN_RESERVE",
  "TOKEN_RELEASE",
  "TOKEN_CONSUME",
  "TOKEN_CONSUME_AVAILABLE",
  "MEMBERSHIP_CYCLE_GRANT",
  "IDENTITY_VERIFICATION_BONUS",
  "PAYOUT_VERIFICATION_BONUS",
  "ADMIN_ADJUSTMENT_CREDIT",
  "ADMIN_ADJUSTMENT_DEBIT",
  "PRIORITY_BID_RESERVE",
  "PRIORITY_BID_INCREASE_RESERVE",
  "PRIORITY_BID_RELEASE",
  "PRIORITY_BID_CONSUME",
  /** Phase 5: normal priced-bid application (NOT Priority Bid). */
  "NORMAL_APPLICATION_CONSUME",
  "NORMAL_APPLICATION_REFUND",
]);

const WORK_TOKEN_LEDGER_EVENT_TYPE_SET = new Set(WORK_TOKEN_LEDGER_EVENT_TYPES);

/** Default event type for generic reserve / increase / release / consume primitives. */
const DEFAULT_RESERVE_EVENT = "TOKEN_RESERVE";
const DEFAULT_INCREASE_RESERVE_EVENT = "TOKEN_RESERVE";
const DEFAULT_RELEASE_EVENT = "TOKEN_RELEASE";
const DEFAULT_CONSUME_EVENT = "TOKEN_CONSUME";
const DEFAULT_CREDIT_EVENT = "TOKEN_CREDIT";

const CREDIT_EVENTS = Object.freeze([
  "TOKEN_CREDIT",
  "MEMBERSHIP_CYCLE_GRANT",
  "IDENTITY_VERIFICATION_BONUS",
  "PAYOUT_VERIFICATION_BONUS",
  "ADMIN_ADJUSTMENT_CREDIT",
  "NORMAL_APPLICATION_REFUND",
]);

const RESERVE_EVENTS = Object.freeze([
  "TOKEN_RESERVE",
  "PRIORITY_BID_RESERVE",
  "PRIORITY_BID_INCREASE_RESERVE",
]);

const RELEASE_EVENTS = Object.freeze(["TOKEN_RELEASE", "PRIORITY_BID_RELEASE"]);
const CONSUME_RESERVED_EVENTS = Object.freeze(["TOKEN_CONSUME", "PRIORITY_BID_CONSUME"]);
const CONSUME_AVAILABLE_EVENTS = Object.freeze([
  "TOKEN_CONSUME_AVAILABLE",
  "ADMIN_ADJUSTMENT_DEBIT",
  "NORMAL_APPLICATION_CONSUME",
]);

const WORK_TOKEN_ERROR_CODES = Object.freeze({
  INVALID_WORK_TOKEN_AMOUNT: "INVALID_WORK_TOKEN_AMOUNT",
  INVALID_WORK_TOKEN_REFERENCE: "INVALID_WORK_TOKEN_REFERENCE",
  INVALID_WORK_TOKEN_EVENT: "INVALID_WORK_TOKEN_EVENT",
  INVALID_WORK_TOKEN_IDEMPOTENCY_KEY: "INVALID_WORK_TOKEN_IDEMPOTENCY_KEY",
  INSUFFICIENT_WORK_TOKENS: "INSUFFICIENT_WORK_TOKENS",
  WORK_TOKEN_RESERVATION_NOT_FOUND: "WORK_TOKEN_RESERVATION_NOT_FOUND",
  WORK_TOKEN_RESERVATION_ALREADY_RELEASED: "WORK_TOKEN_RESERVATION_ALREADY_RELEASED",
  WORK_TOKEN_RESERVATION_ALREADY_CONSUMED: "WORK_TOKEN_RESERVATION_ALREADY_CONSUMED",
  WORK_TOKEN_RESERVATION_NOT_ACTIVE: "WORK_TOKEN_RESERVATION_NOT_ACTIVE",
  WORK_TOKEN_RESERVATION_OWNERSHIP_CONFLICT: "WORK_TOKEN_RESERVATION_OWNERSHIP_CONFLICT",
  WORK_TOKEN_IDEMPOTENCY_CONFLICT: "WORK_TOKEN_IDEMPOTENCY_CONFLICT",
  WORK_TOKEN_WALLET_INTEGRITY_MISMATCH: "WORK_TOKEN_WALLET_INTEGRITY_MISMATCH",
  INVALID_FREELANCER: "INVALID_FREELANCER",
  NORMAL_APPLICATION_TOKEN_PRICING_UNAVAILABLE: "NORMAL_APPLICATION_TOKEN_PRICING_UNAVAILABLE",
  NORMAL_APPLICATION_REFUND_NOT_ELIGIBLE: "NORMAL_APPLICATION_REFUND_NOT_ELIGIBLE",
  NORMAL_APPLICATION_NOT_CHARGED: "NORMAL_APPLICATION_NOT_CHARGED",
  FUTURE_NON_FULL_REFUND_ROUNDING_POLICY_REQUIRED: "FUTURE_NON_FULL_REFUND_ROUNDING_POLICY_REQUIRED",
});

/** Phase 5 reference types for ledger + snapshot linkage. */
const NORMAL_APPLICATION_REFERENCE_TYPES = Object.freeze({
  BID: "order_freelancer_bid",
  ORDER: "order",
});

const NORMAL_APPLICATION_COST_ROUNDING = "CEIL";
/**
 * Snapshot rounding marker when configured refund % is exactly 100:
 * refund_tokens === token_cost (no fractional math).
 * Non-100 snapshots use POLICY_PENDING until a future rounding rule is approved.
 */
const NORMAL_APPLICATION_REFUND_ROUNDING_FULL = "FULL";
const NORMAL_APPLICATION_REFUND_ROUNDING_POLICY_PENDING = "POLICY_PENDING";
/** @deprecated Do not use as business source of truth — read economy settings instead. */
const NORMAL_APPLICATION_REFUND_ROUNDING = NORMAL_APPLICATION_REFUND_ROUNDING_FULL;
const NORMAL_APPLICATION_CONSUME_EVENT = "NORMAL_APPLICATION_CONSUME";
const NORMAL_APPLICATION_REFUND_EVENT = "NORMAL_APPLICATION_REFUND";

function balanceEffectForEvent(eventType) {
  const t = String(eventType || "");
  if (CREDIT_EVENTS.includes(t)) return "credit_available";
  if (RESERVE_EVENTS.includes(t)) return "reserve";
  if (RELEASE_EVENTS.includes(t)) return "release";
  if (CONSUME_RESERVED_EVENTS.includes(t)) return "consume_reserved";
  if (CONSUME_AVAILABLE_EVENTS.includes(t)) return "consume_available";
  return null;
}

function isValidWorkTokenLedgerEvent(eventType) {
  return WORK_TOKEN_LEDGER_EVENT_TYPE_SET.has(String(eventType || "").trim());
}

module.exports = {
  WORK_TOKEN_RESERVATION_STATUSES,
  WORK_TOKEN_BALANCE_EFFECTS,
  WORK_TOKEN_LEDGER_EVENT_TYPES,
  WORK_TOKEN_LEDGER_EVENT_TYPE_SET,
  DEFAULT_RESERVE_EVENT,
  DEFAULT_INCREASE_RESERVE_EVENT,
  DEFAULT_RELEASE_EVENT,
  DEFAULT_CONSUME_EVENT,
  DEFAULT_CREDIT_EVENT,
  CREDIT_EVENTS,
  RESERVE_EVENTS,
  RELEASE_EVENTS,
  CONSUME_RESERVED_EVENTS,
  CONSUME_AVAILABLE_EVENTS,
  WORK_TOKEN_ERROR_CODES,
  NORMAL_APPLICATION_REFERENCE_TYPES,
  NORMAL_APPLICATION_COST_ROUNDING,
  NORMAL_APPLICATION_REFUND_ROUNDING,
  NORMAL_APPLICATION_REFUND_ROUNDING_FULL,
  NORMAL_APPLICATION_REFUND_ROUNDING_POLICY_PENDING,
  NORMAL_APPLICATION_CONSUME_EVENT,
  NORMAL_APPLICATION_REFUND_EVENT,
  balanceEffectForEvent,
  isValidWorkTokenLedgerEvent,
};
