const ARTICLE_SUBMISSION_STATUSES = Object.freeze([
  "submitted",
  "revision_requested",
  "approved",
  "rejected",
]);

const ARTICLE_SUBMISSION_EDITABLE_STATUSES = Object.freeze([
  "submitted",
  "revision_requested",
]);

const ARTICLE_SUBMISSION_APPROVABLE_STATUS = "submitted";

const ARTICLE_APPLICATION_STATUSES_CAN_SUBMIT_MANUSCRIPT = Object.freeze([
  "selected",
  "assigned",
  "writing",
  "submitted",
  "under_review",
  "revision_requested",
]);

const ARTICLE_SUBMISSION_TITLE_MAX = 120;
const ARTICLE_SUBMISSION_TITLE_MIN = 3;
const ARTICLE_SUBMISSION_CONTENT_MAX = 200000;
const ARTICLE_SUBMISSION_CONTENT_MIN_CHARS = 50;

const ARTICLE_SUBMISSION_ERROR_CODES = Object.freeze({
  ARTICLE_FINAL_CONTENT_REQUIRED: "ARTICLE_FINAL_CONTENT_REQUIRED",
  ARTICLE_SUBMISSION_NOT_ALLOWED: "ARTICLE_SUBMISSION_NOT_ALLOWED",
  ARTICLE_SUBMISSION_SCHEMA_NOT_READY: "ARTICLE_SUBMISSION_SCHEMA_NOT_READY",
  ARTICLE_SUBMISSION_INVALID: "ARTICLE_SUBMISSION_INVALID",
  ARTICLE_SUBMISSION_NOT_FOUND: "ARTICLE_SUBMISSION_NOT_FOUND",
  ARTICLE_SUBMISSION_NOT_REVISABLE: "ARTICLE_SUBMISSION_NOT_REVISABLE",
  MISSING_FINAL_ARTICLE_CONTENT: "MISSING_FINAL_ARTICLE_CONTENT",
});

function countWords(text) {
  return String(text || "")
    .trim()
    .split(/\s+/)
    .filter(Boolean).length;
}

module.exports = {
  ARTICLE_SUBMISSION_STATUSES,
  ARTICLE_SUBMISSION_EDITABLE_STATUSES,
  ARTICLE_SUBMISSION_APPROVABLE_STATUS,
  ARTICLE_APPLICATION_STATUSES_CAN_SUBMIT_MANUSCRIPT,
  ARTICLE_SUBMISSION_TITLE_MAX,
  ARTICLE_SUBMISSION_TITLE_MIN,
  ARTICLE_SUBMISSION_CONTENT_MAX,
  ARTICLE_SUBMISSION_CONTENT_MIN_CHARS,
  ARTICLE_SUBMISSION_ERROR_CODES,
  countWords,
};
