/**
 * Phase B5 — Marketplace Article Applications constants.
 *
 * Owner-approved Bid policy (wired when engines ON + Migration 150 applied):
 *   ARTICLE_APPLICATION_BID_COST = 1 (flat; first valid application only)
 *   no-selection refund 100% when Article closes/cancels with no Freelancer selected
 *   withdrawal / rejection / loser refund = NONE
 *
 * Access level is eligibility only — not pricing.
 * Activation requires BOTH article_applications_enabled AND bid_credits_enabled (fail-closed).
 */

const ARTICLE_APPLICATION_STATUSES = Object.freeze([
  "pending",
  "selected",
  "rejected",
  "withdrawn",
  "cancelled",
]);

const ARTICLE_APPLICATION_STATUS_SET = new Set(ARTICLE_APPLICATION_STATUSES);

const ARTICLE_APPLICATION_IDEMPOTENCY_PREFIX = "article_application";

const ARTICLE_APPLICATION_BID_COST = 1;
const ARTICLE_APPLICATION_BID_ECONOMICS_SCHEMA = "IMPLEMENTED_PENDING_MIGRATION_150";
const ARTICLE_APPLICATION_BID_ECONOMICS_RUNTIME = "WIRED";

const ARTICLE_VALUE_TO_BID_COST_MAPPING = "NONE";
const ARTICLE_LEVEL_TO_BID_COST_MAPPING = "NONE";

const ARTICLE_APPLICATION_EDIT_ADDITIONAL_BID_COST = 0;
const ARTICLE_APPLICATION_WITHDRAWAL_REFUND = "NONE";
const ARTICLE_APPLICATION_REJECTION_REFUND = "NONE";
const ARTICLE_APPLICATION_LOSER_REFUND = "NONE";
const ARTICLE_APPLICATION_NO_SELECTION_REFUND = "100_PERCENT";
const ARTICLE_APPLICATION_NO_SELECTION_REFUND_BID_QUANTITY = 1;
const ARTICLE_APPLICATION_NO_SELECTION_COMPENSATING_GRANT_DAYS = 30;

const ARTICLE_APPLICATION_BID_CONSUME_EVENT = "ARTICLE_APPLICATION_BID_CONSUME";
const ARTICLE_APPLICATION_BID_REFUND_EVENT = "ARTICLE_APPLICATION_BID_REFUND";
const ARTICLE_APPLICATION_REFUND_GRANT_SOURCE = "article_application_refund";

const ARTICLE_APPLICATION_BID_CONSUME_IDEMPOTENCY_PREFIX = "article_application_bid_consume";
const ARTICLE_APPLICATION_BID_REFUND_IDEMPOTENCY_PREFIX = "article_application_bid_refund";

const ARTICLE_APPLICATION_FREE_FALLBACK_WHEN_BID_ENGINE_OFF = "NO";
const ARTICLE_APPLICATION_ACTIVATION_REQUIREMENT =
  "ARTICLE_APPLICATIONS_AND_BID_CREDITS_ENABLED";
const ARTICLE_APPLICATION_BID_HISTORICAL_BACKFILL = "NONE";

const ARTICLE_WORK_TOKEN_ENTRY = "CANCELLED";
const ACTIVE_ARTICLE_WORK_TOKEN_RUNTIME = "NONE";
const ARTICLE_APPLICATION_HISTORICAL_BACKFILL = "NONE";
const ARTICLE_PRIORITY_BOOST = "NOT_IMPLEMENTED";
const ARTICLE_FAIR_DISTRIBUTION = "NOT_IMPLEMENTED";
const ARTICLE_MEMBERSHIP_LEVEL_GATE = "ENFORCED";
const ARTICLE_SELECTION_AUTHORITY = "SUPER_ADMIN_EXPLICIT";
const ARTICLE_AUTOMATIC_WINNER = "NONE";
const ARTICLE_APPLICATIONS_ENGINE = "DORMANT";

const ARTICLE_APPLICATION_ERROR_CODES = Object.freeze({
  ARTICLE_APPLICATIONS_ENGINE_OFF: "ARTICLE_APPLICATIONS_ENGINE_OFF",
  ARTICLE_APPLICATIONS_SCHEMA_NOT_READY: "ARTICLE_APPLICATIONS_SCHEMA_NOT_READY",
  ARTICLE_BID_ECONOMY_DISABLED: "ARTICLE_BID_ECONOMY_DISABLED",
  ARTICLE_BID_ECONOMICS_SCHEMA_NOT_READY: "ARTICLE_BID_ECONOMICS_SCHEMA_NOT_READY",
  ARTICLE_NOT_FOUND: "ARTICLE_NOT_FOUND",
  ARTICLE_NOT_OPEN_FOR_APPLICATIONS: "ARTICLE_NOT_OPEN_FOR_APPLICATIONS",
  ARTICLE_FAKE_TRAINING_FORBIDDEN: "ARTICLE_FAKE_TRAINING_FORBIDDEN",
  ARTICLE_ACCESS_LEVEL_INSUFFICIENT: "ARTICLE_ACCESS_LEVEL_INSUFFICIENT",
  ARTICLE_NO_USABLE_MEMBERSHIP: "ARTICLE_NO_USABLE_MEMBERSHIP",
  ARTICLE_APPLICATION_EXISTS: "ARTICLE_APPLICATION_EXISTS",
  ARTICLE_APPLICATION_NOT_FOUND: "ARTICLE_APPLICATION_NOT_FOUND",
  ARTICLE_APPLICATION_NOT_EDITABLE: "ARTICLE_APPLICATION_NOT_EDITABLE",
  ARTICLE_APPLICATION_NOT_WITHDRAWABLE: "ARTICLE_APPLICATION_NOT_WITHDRAWABLE",
  ARTICLE_APPLICATION_NOT_SELECTABLE: "ARTICLE_APPLICATION_NOT_SELECTABLE",
  ARTICLE_APPLICATION_WRONG_COLLECTION_ROUND: "ARTICLE_APPLICATION_WRONG_COLLECTION_ROUND",
  ARTICLE_FAIR_SELECTION_OVERRIDE_REASON_REQUIRED: "ARTICLE_FAIR_SELECTION_OVERRIDE_REASON_REQUIRED",
  ARTICLE_METADATA_FROZEN: "ARTICLE_METADATA_FROZEN",
  ARTICLE_BID_ECONOMICS_NOT_WIRED: "ARTICLE_BID_ECONOMICS_NOT_WIRED",
});

function roundKeySuffix(collectionRoundId) {
  return collectionRoundId != null && collectionRoundId !== ""
    ? `:round:${Number(collectionRoundId)}`
    : "";
}

function buildArticleApplicationIdempotencyKey(articleId, freelancerUserId, collectionRoundId) {
  return `${ARTICLE_APPLICATION_IDEMPOTENCY_PREFIX}:article:${Number(articleId)}:freelancer:${Number(freelancerUserId)}${roundKeySuffix(collectionRoundId)}`;
}

function buildArticleApplicationBidConsumeIdempotencyKey(articleId, freelancerUserId, collectionRoundId) {
  return `${ARTICLE_APPLICATION_BID_CONSUME_IDEMPOTENCY_PREFIX}:article:${Number(articleId)}:freelancer:${Number(freelancerUserId)}${roundKeySuffix(collectionRoundId)}`;
}

function buildArticleApplicationBidRefundIdempotencyKey(articleId, freelancerUserId, collectionRoundId) {
  return `${ARTICLE_APPLICATION_BID_REFUND_IDEMPOTENCY_PREFIX}:article:${Number(articleId)}:freelancer:${Number(freelancerUserId)}${roundKeySuffix(collectionRoundId)}`;
}

function isValidArticleApplicationStatus(value) {
  return ARTICLE_APPLICATION_STATUS_SET.has(String(value || "").trim());
}

module.exports = {
  ARTICLE_APPLICATION_STATUSES,
  ARTICLE_APPLICATION_STATUS_SET,
  ARTICLE_APPLICATION_IDEMPOTENCY_PREFIX,
  ARTICLE_APPLICATION_BID_COST,
  ARTICLE_APPLICATION_BID_ECONOMICS_SCHEMA,
  ARTICLE_APPLICATION_BID_ECONOMICS_RUNTIME,
  ARTICLE_VALUE_TO_BID_COST_MAPPING,
  ARTICLE_LEVEL_TO_BID_COST_MAPPING,
  ARTICLE_APPLICATION_EDIT_ADDITIONAL_BID_COST,
  ARTICLE_APPLICATION_WITHDRAWAL_REFUND,
  ARTICLE_APPLICATION_REJECTION_REFUND,
  ARTICLE_APPLICATION_LOSER_REFUND,
  ARTICLE_APPLICATION_NO_SELECTION_REFUND,
  ARTICLE_APPLICATION_NO_SELECTION_REFUND_BID_QUANTITY,
  ARTICLE_APPLICATION_NO_SELECTION_COMPENSATING_GRANT_DAYS,
  ARTICLE_APPLICATION_BID_CONSUME_EVENT,
  ARTICLE_APPLICATION_BID_REFUND_EVENT,
  ARTICLE_APPLICATION_REFUND_GRANT_SOURCE,
  ARTICLE_APPLICATION_BID_CONSUME_IDEMPOTENCY_PREFIX,
  ARTICLE_APPLICATION_BID_REFUND_IDEMPOTENCY_PREFIX,
  ARTICLE_APPLICATION_FREE_FALLBACK_WHEN_BID_ENGINE_OFF,
  ARTICLE_APPLICATION_ACTIVATION_REQUIREMENT,
  ARTICLE_APPLICATION_BID_HISTORICAL_BACKFILL,
  ARTICLE_WORK_TOKEN_ENTRY,
  ACTIVE_ARTICLE_WORK_TOKEN_RUNTIME,
  ARTICLE_APPLICATION_HISTORICAL_BACKFILL,
  ARTICLE_PRIORITY_BOOST,
  ARTICLE_FAIR_DISTRIBUTION,
  ARTICLE_MEMBERSHIP_LEVEL_GATE,
  ARTICLE_SELECTION_AUTHORITY,
  ARTICLE_AUTOMATIC_WINNER,
  ARTICLE_APPLICATIONS_ENGINE,
  ARTICLE_APPLICATION_ERROR_CODES,
  buildArticleApplicationIdempotencyKey,
  buildArticleApplicationBidConsumeIdempotencyKey,
  buildArticleApplicationBidRefundIdempotencyKey,
  isValidArticleApplicationStatus,
};
