/**
 * Phase 8 Elite Direct Orders — constants.
 */

const ELITE_OFFER_STATUSES = Object.freeze([
  "pending",
  "accepted",
  "declined",
  "expired",
  "cancelled",
  "ineligible",
]);

const ELITE_OFFER_TERMINAL_STATUSES = Object.freeze([
  "accepted",
  "declined",
  "expired",
  "cancelled",
  "ineligible",
]);

const ELITE_ENTITLEMENT_EVENT_TYPES = Object.freeze(["reserve", "consume", "release"]);

const ELITE_DIRECT_ORDER_ERROR_CODES = Object.freeze({
  ELITE_ENGINE_OFF: "ELITE_ENGINE_OFF",
  ELITE_DIRECT_ORDER_ENTITLEMENT_UNAVAILABLE: "ELITE_DIRECT_ORDER_ENTITLEMENT_UNAVAILABLE",
  ELITE_TARGET_INELIGIBLE: "ELITE_TARGET_INELIGIBLE",
  ELITE_INELIGIBLE_AT_ACCEPT: "ELITE_INELIGIBLE_AT_ACCEPT",
  ELITE_OFFER_NOT_FOUND: "ELITE_OFFER_NOT_FOUND",
  ELITE_OFFER_NOT_PENDING: "ELITE_OFFER_NOT_PENDING",
  ELITE_OFFER_EXPIRED: "ELITE_OFFER_EXPIRED",
  ELITE_ACTIVE_OFFER_EXISTS: "ELITE_ACTIVE_OFFER_EXISTS",
  ELITE_UNAUTHORIZED_CREATOR: "ELITE_UNAUTHORIZED_CREATOR",
  ELITE_UNAUTHORIZED_TARGET: "ELITE_UNAUTHORIZED_TARGET",
  ELITE_FAKE_TRAINING_FORBIDDEN: "ELITE_FAKE_TRAINING_FORBIDDEN",
  PRIORITY_BID_AUCTION_ACTIVE: "PRIORITY_BID_AUCTION_ACTIVE",
  ELITE_ORDER_NOT_ELIGIBLE: "ELITE_ORDER_NOT_ELIGIBLE",
  ELITE_SCHEMA_MISSING: "ELITE_SCHEMA_MISSING",
});

const ELITE_REASON_CODES = Object.freeze({
  FREELANCER_DECLINED: "FREELANCER_DECLINED",
  OFFER_EXPIRED: "OFFER_EXPIRED",
  CREATOR_CANCELLED: "CREATOR_CANCELLED",
  ORDER_CANCELLED: "ORDER_CANCELLED",
  ELITE_INELIGIBLE_AT_ACCEPT: "ELITE_INELIGIBLE_AT_ACCEPT",
  ACCEPTED: "ACCEPTED",
});

/** Elite Direct Order acceptance costs zero Work Tokens. */
const ELITE_DIRECT_ORDER_WORK_TOKEN_COST = 0;

module.exports = {
  ELITE_OFFER_STATUSES,
  ELITE_OFFER_TERMINAL_STATUSES,
  ELITE_ENTITLEMENT_EVENT_TYPES,
  ELITE_DIRECT_ORDER_ERROR_CODES,
  ELITE_REASON_CODES,
  ELITE_DIRECT_ORDER_WORK_TOKEN_COST,
};
